### PR TITLE
use sigtimedwait instead of pthread_cond_timedwait 

### PR DESCRIPTION
**Pull request by arichardson**
pthread mutexes should not be used inside signal handlers

### CODE REVIEW

**Comment by arichardson** [comment]
updated to remove usage of pthread.

However when I run ldd on xorg-launch-helper it is still linked. grepping through all files shows no mention of it, I am guessing it is linked due to either -lsystemd-daemon or -lrt

**Comment by arichardson** [comment]
Amending and force pushing seems to have removed the old request. Sorry about that, I am quite new to GitHub and am not sure what the best procedure is.

**Comment by sofar** [comment]
No problem, github isn't exactly the most logical way to do this, nor the easiest - I take patches by e-mail as well - which works just as easy.

BTW, what is actually the issue with pthreads in signal handlers? are all the threads in an inconsistent state or locked when a signal arrives?

The patch looks OK to me btw, I'll try and find some time to test tomorrow.

**Comment by sofar** [comment]
hmmm, I just found: http://maxim.int.ru/bookshelf/PthreadsProgram/htm/r_40.html

very interesting read. Did you actually encounter a bug due to this?

**Comment by arichardson** [comment]
I didn't actually encounter a bug here, but I have in other software.
I just noticed the pthread calls in the signal handler and decided to change it since it is not much work.

Probably the only way xorg-launch-helper could break is if sigusr1 is delivered just after pthread_mutex_lock. This is quite unlikely, but nevertheless possible.

I tested this patch both with normally launching Xorg and also replacing execv with a series of usleep()+kill(getppid()) calls. Both worked fine for me.

**Pull request merged**
